@echo off

cmake -B build/debug -G Ninja ^
-DSUPERBUILD=ON ^
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
-DCMAKE_BUILD_TYPE=Debug ^
-DAS_COL_MAJOR=ON -DAS_PRECISION_FLOAT=ON

cmake -B build/release -G Ninja ^
-DSUPERBUILD=ON ^
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
-DCMAKE_BUILD_TYPE=Release ^
-DAS_COL_MAJOR=ON -DAS_PRECISION_FLOAT=ON
