#!/bin/bash

cmake -B build/debug -G Ninja \
-DSUPERBUILD=ON \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DCMAKE_BUILD_TYPE=Debug \
-DAS_ROW_MAJOR=ON -DAS_PRECISION_FLOAT=ON

cmake -B build/release -G Ninja \
-DSUPERBUILD=ON \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DCMAKE_BUILD_TYPE=Release \
-DAS_ROW_MAJOR=ON -DAS_PRECISION_FLOAT=ON
